name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Build
        run: |
          cd example
          pod install
          xcodebuild clean build -workspace example.xcworkspace -scheme example -destination "platform=iOS Simulator,name=iPhone 11" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
       
      - name: Lint
        run: |
          set -eo pipefail
          pod lib lint --allow-warnings  
