name: CI
on:
  push:
    branches:
    - master
    
jobs:
  build:
    name: Application build
    runs-on: macOS-latest
    
    steps:
    - name: Checkout repository (#1)
      uses: actions/checkout@v1
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push ZGRatingView.podspec
