name: CI
on:
  pull_request:
    branches:
    - master
    tags:
    - 'v*.*.*'
    
jobs:
  build:
    name: Application build
    runs-on: macOS-latest
    
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.2,name=iPhone X']

    
    steps:
    - name: Checkout repository (#1)
      uses: actions/checkout@v1
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push 
